# Generated by Django 5.2.7 on 2025-10-30 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('join_password', models.CharField(max_length=128)),
                ('notes_password', models.CharField(max_length=128)),
                ('max_members', models.PositiveIntegerField(default=10)),
                ('delegate_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='groups.maingroup')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=200)),
                ('name3', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40, unique=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('courses', models.ManyToManyField(blank=True, to='groups.course')),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_group', to='groups.student')),
                ('main_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='groups.maingroup')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.subgroup'),
        ),
        migrations.CreateModel(
            name='GroupNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='groups.subgroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groups.subgroup')),
            ],
        ),
    ]
